version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.6.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
  # volumes:
  #   - ./data/elastic:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.2.0
    ports:
      - "5601:5601"
  web:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: web.nginx.logs
